spring.application.name=inventory-service

# ==========================================================
# Server
# ==========================================================
server.port=8082

# ==========================================================
# MySQL
# ==========================================================
spring.datasource.url=jdbc:mysql://localhost:3306/smartcart_inventory_db
spring.datasource.username=root
spring.datasource.password=root

# ==========================================================
# JPA / Hibernate
# ==========================================================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================================================
# JWT
# ==========================================================
jwt.secret=SmartCartAI-AuthService-SecretKey-2026-Production-Change-This
jwt.expiration=86400000