package com.smartcart.product.service;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

import org.springframework.security.access.AccessDeniedException;
import org.springframework.stereotype.Service;

import com.smartcart.product.client.InventoryClient;
import com.smartcart.product.dto.InventoryRequest;
import com.smartcart.product.entity.Category;
import com.smartcart.product.entity.Product;
import com.smartcart.product.exception.CategoryNotFoundException;
import com.smartcart.product.exception.DuplicateProductException;
import com.smartcart.product.exception.ProductNotFoundException;
import com.smartcart.product.repository.CategoryRepository;
import com.smartcart.product.repository.ProductRepository;

@Service
public class ProductService {

    private final ProductRepository productRepository;

    private final CategoryRepository categoryRepository;

    private final InventoryClient inventoryClient;

    public ProductService(
            ProductRepository productRepository,
            CategoryRepository categoryRepository,
            InventoryClient inventoryClient) {

        this.productRepository = productRepository;
        this.categoryRepository = categoryRepository;
        this.inventoryClient = inventoryClient;
    }

    // =========================================================
    // CREATE PRODUCT
    // =========================================================

    public Product createProduct(Product product) {

        // Check whether another product already uses this SKU.
        if (productRepository.existsBySku(product.getSku())) {

            throw new DuplicateProductException(
                    "Product already exists with SKU: "
                            + product.getSku());
        }

        // Check whether another product already uses this name.
        if (productRepository.existsByProductName(
                product.getProductName())) {

            throw new DuplicateProductException(
                    "Product already exists with name: "
                            + product.getProductName());
        }

        /*
         * Find the category from Product Service's database.
         *
         * We receive only categoryId from the request and then
         * load the real Category entity from the database.
         */

        Category category = categoryRepository
                .findById(product.getCategory().getCategoryId())

                .orElseThrow(() ->
                        new CategoryNotFoundException(
                                "Category not found with ID: "
                                        + product.getCategory()
                                                .getCategoryId()));

        // Attach the existing category entity to the product.
        product.setCategory(category);

        /*
         * If the seller does not provide a status,
         * automatically make the product ACTIVE.
         */

        if (product.getStatus() == null ||
                product.getStatus().isBlank()) {

            product.setStatus("ACTIVE");
        }

        /*
         * =====================================================
         * SAVE PRODUCT FIRST
         * =====================================================
         *
         * We save the product first because the database generates
         * the productId.
         *
         * Example:
         *
         * Before save:
         * productId = null
         *
         * After save:
         * productId = 5
         *
         * We need this productId when creating inventory.
         */

        Product savedProduct =
                productRepository.save(product);

        /*
         * =====================================================
         * CREATE INITIAL INVENTORY
         * =====================================================
         *
         * Every newly created product should have an inventory
         * record in Inventory Service.
         *
         * We start with:
         *
         * availableQuantity = 0
         * reservedQuantity  = 0
         * reorderLevel      = 10
         *
         * The seller can increase the stock later through
         * Inventory Service.
         */

        InventoryRequest inventoryRequest =
                new InventoryRequest();

        // Use the actual product ID generated by Product Service.
        inventoryRequest.setProductId(
                savedProduct.getProductId());

        // New product starts with zero physical stock.
        inventoryRequest.setAvailableQuantity(0);

        // No stock is reserved when the product is first created.
        inventoryRequest.setReservedQuantity(0);

        // Seller should consider restocking when stock reaches 10.
        inventoryRequest.setReorderLevel(10);

        /*
         * Send the inventory creation request to Inventory Service.
         *
         * FeignClientConfig automatically forwards the Seller's
         * Authorization header/JWT to Inventory Service.
         */

        inventoryClient.createInventory(
                inventoryRequest);

        /*
         * Return the product that was successfully created.
         */

        return savedProduct;
    }

    // =========================================================
    // GET ALL PRODUCTS
    // =========================================================

    public List<Product> getAllProducts() {

        return productRepository.findAll();

    }

    // =========================================================
    // GET PRODUCTS BY SELLER
    // =========================================================

    public List<Product> getProductsBySeller(Long sellerId) {

        /*
         * Retrieve only the products that belong to the
         * specified seller.
         *
         * The repository converts this into a database query
         * using the product's sellerId.
         *
         * Example:
         *
         * sellerId = 8
         *
         *        ↓
         *
         * return products where seller_id = 8
         */

        return productRepository.findBySellerId(sellerId);
    }

    // =========================================================
    // GET PRODUCT BY ID
    // =========================================================

    public Product getProductById(Long productId) {

        return productRepository.findById(productId)

                .orElseThrow(() ->
                        new ProductNotFoundException(
                                "Product not found with ID: "
                                        + productId));
    }

    // =========================================================
    // UPDATE PRODUCT
    // =========================================================

    public Product updateProduct(
            Long productId,
            Product updatedProduct,
            Long authenticatedUserId) {

        /*
         * First find the product that the seller is trying
         * to modify.
         */

        Product existingProduct =
                getProductById(productId);

        /*
         * SECURITY CHECK:
         *
         * The authenticated user's ID must match the product's
         * existing seller ID.
         *
         * This prevents Seller A from modifying Seller B's product.
         */

        verifyProductOwnership(
                existingProduct,
                authenticatedUserId);

        // Check duplicate SKU only when the SKU is actually changed.
        if (!existingProduct.getSku()
                .equals(updatedProduct.getSku())

                && productRepository.existsBySku(
                        updatedProduct.getSku())) {

            throw new DuplicateProductException(
                    "Product already exists with SKU: "
                            + updatedProduct.getSku());
        }

        // Check duplicate product name only when the name is changed.
        if (!existingProduct.getProductName()
                .equalsIgnoreCase(
                        updatedProduct.getProductName())

                && productRepository.existsByProductName(
                        updatedProduct.getProductName())) {

            throw new DuplicateProductException(
                    "Product already exists with name: "
                            + updatedProduct.getProductName());
        }

        /*
         * Find the requested category.
         */

        Category category = categoryRepository
                .findById(
                        updatedProduct
                                .getCategory()
                                .getCategoryId())

                .orElseThrow(() ->
                        new CategoryNotFoundException(
                                "Category not found with ID: "
                                        + updatedProduct
                                                .getCategory()
                                                .getCategoryId()));

        existingProduct.setCategory(category);

        /*
         * IMPORTANT:
         *
         * We deliberately DO NOT update sellerId.
         *
         * Seller ownership must never be changed through
         * the normal product update request.
         */

        existingProduct.setProductName(
                updatedProduct.getProductName());

        existingProduct.setDescription(
                updatedProduct.getDescription());

        existingProduct.setPrice(
                updatedProduct.getPrice());

        existingProduct.setBrand(
                updatedProduct.getBrand());

        existingProduct.setSku(
                updatedProduct.getSku());

        /*
         * Update status only when a valid status was supplied.
         */

        if (updatedProduct.getStatus() != null &&
                !updatedProduct.getStatus().isBlank()) {

            existingProduct.setStatus(
                    updatedProduct.getStatus());
        }

        return productRepository.save(existingProduct);
    }

    // =========================================================
    // DELETE PRODUCT
    // =========================================================

    public void deleteProduct(
            Long productId,
            Long authenticatedUserId) {

        /*
         * Find the product first.
         */

        Product product =
                getProductById(productId);

        /*
         * SECURITY CHECK:
         *
         * Only the seller who owns the product can delete it.
         */

        verifyProductOwnership(
                product,
                authenticatedUserId);

        /*
         * =====================================================
         * DELETE INVENTORY FIRST
         * =====================================================
         *
         * Product Service and Inventory Service use separate
         * databases.
         *
         * Therefore, deleting the Product record does NOT
         * automatically delete its Inventory record.
         *
         * We explicitly tell Inventory Service to remove the
         * inventory belonging to this product.
         */

        inventoryClient.deleteInventory(productId);

        /*
         * =====================================================
         * DELETE PRODUCT
         * =====================================================
         *
         * Inventory has now been removed successfully.
         * We can safely remove the Product record.
         */

        productRepository.delete(product);
    }

    // =========================================================
    // VERIFY PRODUCT OWNERSHIP
    // =========================================================

    private void verifyProductOwnership(
            Product product,
            Long authenticatedUserId) {

        /*
         * Compare:
         *
         * Product sellerId
         *        VS
         * Authenticated user's ID
         *
         * They must be the same.
         */

        if (!product.getSellerId()
                .equals(authenticatedUserId)) {

            throw new AccessDeniedException(
                    "You are not authorized to modify this product");
        }
    }

    // =========================================================
    // SEARCH PRODUCTS
    // =========================================================

    public List<Product> searchProducts(String keyword) {

        /*
         * If no keyword is provided, return all products.
         */

        if (keyword == null || keyword.isBlank()) {

            return productRepository.findAll();
        }

        /*
         * Search by product name OR description.
         */

        return productRepository
                .findByProductNameContainingIgnoreCaseOrDescriptionContainingIgnoreCase(
                        keyword,
                        keyword);
    }

    // =========================================================
    // FILTER PRODUCTS
    // =========================================================

    public List<Product> filterProducts(
            Long categoryId,
            String brand,
            String status,
            BigDecimal minPrice,
            BigDecimal maxPrice) {

        /*
         * Get all products first.
         */

        List<Product> products =
                productRepository.findAll();

        /*
         * This list will contain products that match
         * all requested filters.
         */

        List<Product> filteredProducts =
                new ArrayList<>();

        for (Product product : products) {

            boolean matches = true;

            // -------------------------------------------------
            // Category filter
            // -------------------------------------------------

            if (categoryId != null &&

                    (product.getCategory() == null ||

                            !product.getCategory()
                                    .getCategoryId()
                                    .equals(categoryId))) {

                matches = false;
            }

            // -------------------------------------------------
            // Brand filter
            // -------------------------------------------------

            if (brand != null &&
                    !brand.isBlank() &&

                    (product.getBrand() == null ||

                            !product.getBrand()
                                    .equalsIgnoreCase(brand))) {

                matches = false;
            }

            // -------------------------------------------------
            // Status filter
            // -------------------------------------------------

            if (status != null &&
                    !status.isBlank() &&

                    (product.getStatus() == null ||

                            !product.getStatus()
                                    .equalsIgnoreCase(status))) {

                matches = false;
            }

            // -------------------------------------------------
            // Minimum price filter
            // -------------------------------------------------

            if (minPrice != null &&

                    (product.getPrice() == null ||

                            product.getPrice()
                                    .compareTo(minPrice) < 0)) {

                matches = false;
            }

            // -------------------------------------------------
            // Maximum price filter
            // -------------------------------------------------

            if (maxPrice != null &&

                    (product.getPrice() == null ||

                            product.getPrice()
                                    .compareTo(maxPrice) > 0)) {

                matches = false;
            }

            // Add the product if all filters matched.
            if (matches) {

                filteredProducts.add(product);
            }
        }

        return filteredProducts;
    }

    // =========================================================
    // CHECK INVENTORY AVAILABILITY
    // =========================================================

    public boolean checkInventoryAvailability(
            Long productId,
            Integer quantity) {

        /*
         * First verify that the product exists.
         */

        getProductById(productId);

        /*
         * Then call Inventory Service through Feign.
         */

        return inventoryClient.checkAvailability(
                productId,
                quantity);
    }
}