package com.smartcart.order.jwt;

import io.jsonwebtoken.Claims;
import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.security.Keys;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;

import javax.crypto.SecretKey;
import java.nio.charset.StandardCharsets;

@Component
public class JwtUtil {

    @Value("${jwt.secret}")
    private String secret;

    // =========================================================
    // GET SIGNING KEY
    // =========================================================

    /*
     * Creates the same signing key used by Auth Service.
     *
     * Because all services use the same JWT secret,
     * Order Service can verify the JWT generated by Auth Service.
     */
    private SecretKey getSigningKey() {

        return Keys.hmacShaKeyFor(
                secret.getBytes(StandardCharsets.UTF_8)
        );
    }

    // =========================================================
    // EXTRACT ALL CLAIMS
    // =========================================================

    /*
     * Reads all information stored inside the JWT.
     *
     * This also verifies the JWT signature.
     */
    public Claims extractAllClaims(String token) {

        return Jwts.parser()
                .verifyWith(getSigningKey())
                .build()
                .parseSignedClaims(token)
                .getPayload();
    }

    // =========================================================
    // EXTRACT USERNAME / EMAIL
    // =========================================================

    /*
     * Email is stored as the JWT subject.
     */
    public String extractUsername(String token) {

        return extractAllClaims(token)
                .getSubject();
    }

    // =========================================================
    // EXTRACT USER ID
    // =========================================================

    /*
     * Auth Service stores the database user ID inside:
     *
     * "userId"
     *
     * We will use this value to identify the authenticated seller.
     */
    public Long extractUserId(String token) {

        return extractAllClaims(token)
                .get("userId", Long.class);
    }

    // =========================================================
    // EXTRACT ROLE
    // =========================================================

    /*
     * Auth Service stores the user's role inside:
     *
     * "role"
     *
     * Example:
     *
     * CUSTOMER
     * SELLER
     * ADMIN
     */
    public String extractRole(String token) {

        return extractAllClaims(token)
                .get("role", String.class);
    }

    // =========================================================
    // VALIDATE TOKEN
    // =========================================================

    /*
     * Checks whether the JWT can be successfully parsed.
     *
     * If the signature is invalid, token is malformed,
     * or another parsing problem occurs, validation fails.
     */
    public boolean isTokenValid(String token) {

        try {

            extractAllClaims(token);

            return true;

        } catch (Exception e) {

            return false;
        }
    }
}